version: "3"

services:
  database:
    container_name: database
    image: mysql:5.7
    restart: unless-stopped
    ports:
     - 3307:3307
    environment:
     - MYSQL_ROOT_PASSWORD=0000
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
    volumes:
     - db:/var/lib/mysql
     
  spring_app:
    image: abdelmatine/achat-1.0
    container_name: achatspring
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3307/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC,
     - spring.datasource.username = root,
     - spring.datasource.password = 0000
    ports:
     - 8089:8089
    depends_on:
     - database

     
  angular_app:
   image: abdelmatine/crudtutofront:v1
   container_name: achatangular
   restart: on-failure
   ports:
    - 4200:80
   depends_on:
    - spring_app
       
volumes:
  db:
    
    